import { StyleSheet } from "react-native";
import { getHeight, getWidth, colors } from "../../utils";

const styles = (colorScheme: any) =>
  StyleSheet.create({
    newPostContainer: {
      width: "100%",
      height: "100%",
      backgroundColor: colorScheme === "light" ? colors.white : colors.black,
      paddingTop: getHeight(30),
      paddingLeft: getWidth(20),
      paddingRight: getWidth(20),
      zIndex: 3,
    },
    newPostContainerInner: {
      width: "100%",
      height: "100%",
      backgroundColor: colorScheme === "light" ? colors.white : colors.black,
      marginTop: getHeight(30),
      marginRight: getWidth(10),
      textAlign: "center",
    },
    newPostCancel: {
      color: colors.cherry,
      fontSize: getHeight(15),
      marginBottom: getHeight(20),
    },
    newPostUserImage: {
      width: 50,
      height: 50,
      backgroundColor: colors.dork,
      borderRadius: 100,
    },
    newPostInput: {
      width: getWidth(230),
      right: 0,
      paddingLeft: getWidth(10),
      paddingRight: getWidth(10),
      paddingTop: getHeight(10),
      paddingBottom: getHeight(10),
      marginLeft: getWidth(10),
      justifyContent: "flex-end",
      color: colorScheme === "light" ? colors.black : colors.white,
    },
    newPostAlign: {
      padding: 0,
      flexDirection: "row",
    },
    newPostSend: {
      top: 0,
      right: 0,
      zIndex: 2,
      color: colors.white,
      borderRadius: 100,
      alignItems: "center",
      alignContent: "center",
      justifyContent: "center",
      width: 100,
      height: 30,
      backgroundColor: colors.cherry,
    },
    newPostSendDisabled: {
      top: 0,
      right: 0,
      zIndex: 2,
      color: colors.white,
      borderRadius: 100,
      alignItems: "center",
      alignContent: "center",
      justifyContent: "center",
      width: 100,
      height: 30,
      backgroundColor: colorScheme === "light" ? colors.lightGray : colors.grok,
    },
    newPostSendText: {
      color: colors.white,
    },
    imageIcon: {},
    imageIconContainer: {
      width: 50,
      height: 50,
      position: "absolute",
      marginRight: getWidth(10),
      right: 0,
      bottom: 0,
      borderColor: colors.lightGray,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: getHeight(100),
      marginBottom: getHeight(100),
    },
    imageIconContainerSuccess: {
      width: 50,
      height: 50,
      position: "absolute",
      marginRight: getWidth(10),
      right: 0,
      bottom: 0,
      borderColor: colors.cherry,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: getHeight(100),
      marginBottom: getHeight(100),
    },
    align: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    noPostProfileImage: {
      width: 50,
      height: 50,
      borderColor: colors.dork,
      borderWidth: 1,
      borderRadius: 100,
      alignItems: "center",
      justifyContent: "center",
    },
  });

export default styles;
